# This is a basic workflow to help you get started with Actions

name: MANUAL
  # Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  staging:
    needs: printInputs
    runs-on: ubuntu-latest
    name: Deploy to staging
    environment:
        name: STAGING
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  production:
    needs: staging
    runs-on: ubuntu-latest
    name: Deploy to prod
    environment:
        name: PRODUCTION
    steps:
    # Download artifacts
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"